"""initial schema

Revision ID: 91928d8bc3eb
Revises: 
Create Date: 2026-06-28 18:16:42.173207
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91928d8bc3eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('code', 'version', name='prompt_code_version')
    )
    op.create_table('roles',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('rule_versions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_versions')),
    sa.UniqueConstraint('code', 'version', name='rule_code_version')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('audit_logs',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address_masked', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('before_data_masked', sa.JSON(), nullable=True),
    sa.Column('after_data_masked', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_logs_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('bidders',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('unified_credit_code_masked', sa.String(length=64), nullable=True),
    sa.Column('unified_credit_code_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_bidders_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bidders')),
    sa.UniqueConstraint('project_id', 'name', name='bidder_project_name')
    )
    op.create_index(op.f('ix_bidders_unified_credit_code_hmac'), 'bidders', ['unified_credit_code_hmac'], unique=False)
    op.create_table('processing_runs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_masked', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_processing_runs_project_id_projects')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_processing_runs_requested_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_runs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_processing_runs_idempotency_key'))
    )
    op.create_index(op.f('ix_processing_runs_project_id'), 'processing_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_processing_runs_status'), 'processing_runs', ['status'], unique=False)
    op.create_table('findings',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requires_materials', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_findings_project_id_projects')),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_findings_run_id_processing_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_project_id'), 'findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_findings_risk_level'), 'findings', ['risk_level'], unique=False)
    op.create_index(op.f('ix_findings_rule_code'), 'findings', ['rule_code'], unique=False)
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('generated_reports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('template_version', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('generated_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_generated_reports_generated_by_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_generated_reports_project_id_projects')),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_generated_reports_run_id_processing_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_reports'))
    )
    op.create_index(op.f('ix_generated_reports_project_id'), 'generated_reports', ['project_id'], unique=False)
    op.create_table('processing_tasks',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_key', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_processing_tasks_run_id_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_tasks')),
    sa.UniqueConstraint('run_id', 'task_key', name='processing_run_task_key')
    )
    op.create_index(op.f('ix_processing_tasks_run_id'), 'processing_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_processing_tasks_status'), 'processing_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_processing_tasks_task_type'), 'processing_tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_processing_tasks_trace_id'), 'processing_tasks', ['trace_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('bidder_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], name=op.f('fk_source_documents_bidder_id_bidders')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_source_documents_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_source_documents_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('project_id', 'sha256', 'version_number', name='document_digest_version')
    )
    op.create_index(op.f('ix_source_documents_document_type'), 'source_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_source_documents_sha256'), 'source_documents', ['sha256'], unique=False)
    op.create_table('cross_document_matches',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('match_type', sa.String(length=100), nullable=False),
    sa.Column('left_document_id', sa.Uuid(), nullable=False),
    sa.Column('right_document_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_document_id'], ['source_documents.id'], name=op.f('fk_cross_document_matches_left_document_id_source_documents')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cross_document_matches_project_id_projects')),
    sa.ForeignKeyConstraint(['right_document_id'], ['source_documents.id'], name=op.f('fk_cross_document_matches_right_document_id_source_documents')),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_cross_document_matches_run_id_processing_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cross_document_matches'))
    )
    op.create_index(op.f('ix_cross_document_matches_match_type'), 'cross_document_matches', ['match_type'], unique=False)
    op.create_index(op.f('ix_cross_document_matches_project_id'), 'cross_document_matches', ['project_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('pdf_page_number', sa.Integer(), nullable=False),
    sa.Column('printed_page_number', sa.String(length=64), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_document_pages_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'pdf_page_number', name='document_pdf_page')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_document_versions_document_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name='document_version_number')
    )
    op.create_index(op.f('ix_document_versions_sha256'), 'document_versions', ['sha256'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('fact_type', sa.String(length=100), nullable=False),
    sa.Column('normalized_value', sa.JSON(), nullable=False),
    sa.Column('display_value_masked', sa.Text(), nullable=True),
    sa.Column('sensitive_value_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_extracted_facts_document_id_source_documents')),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_extracted_facts_run_id_processing_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_facts'))
    )
    op.create_index(op.f('ix_extracted_facts_document_id'), 'extracted_facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_fact_type'), 'extracted_facts', ['fact_type'], unique=False)
    op.create_index(op.f('ix_extracted_facts_run_id'), 'extracted_facts', ['run_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_sensitive_value_hmac'), 'extracted_facts', ['sensitive_value_hmac'], unique=False)
    op.create_table('model_call_logs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('page_range', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_masked', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_model_call_logs_document_id_source_documents')),
    sa.ForeignKeyConstraint(['run_id'], ['processing_runs.id'], name=op.f('fk_model_call_logs_run_id_processing_runs')),
    sa.ForeignKeyConstraint(['task_id'], ['processing_tasks.id'], name=op.f('fk_model_call_logs_task_id_processing_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_call_logs'))
    )
    op.create_index(op.f('ix_model_call_logs_run_id'), 'model_call_logs', ['run_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('revised_risk_level', sa.String(length=32), nullable=True),
    sa.Column('revised_description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('finding_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_review_decisions_finding_id_findings')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_decisions_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    op.create_index('ix_review_decision_finding_created', 'review_decisions', ['finding_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_decisions_finding_id'), 'review_decisions', ['finding_id'], unique=False)
    op.create_table('evidence',
    sa.Column('fact_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('pdf_page_number', sa.Integer(), nullable=False),
    sa.Column('printed_page_number', sa.String(length=64), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('quote_masked', sa.Text(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=1000), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_evidence_document_id_source_documents')),
    sa.ForeignKeyConstraint(['fact_id'], ['extracted_facts.id'], name=op.f('fk_evidence_fact_id_extracted_facts')),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], name=op.f('fk_evidence_page_id_document_pages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_document_id'), 'evidence', ['document_id'], unique=False)
    op.create_table('personnel_records',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('bidder_id', sa.Uuid(), nullable=False),
    sa.Column('name_masked', sa.String(length=200), nullable=False),
    sa.Column('name_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('role_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('source_fact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['bidders.id'], name=op.f('fk_personnel_records_bidder_id_bidders')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_personnel_records_project_id_projects')),
    sa.ForeignKeyConstraint(['source_fact_id'], ['extracted_facts.id'], name=op.f('fk_personnel_records_source_fact_id_extracted_facts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personnel_records'))
    )
    op.create_index(op.f('ix_personnel_records_bidder_id'), 'personnel_records', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_personnel_records_name_hmac'), 'personnel_records', ['name_hmac'], unique=False)
    op.create_index(op.f('ix_personnel_records_project_id'), 'personnel_records', ['project_id'], unique=False)
    op.create_table('credential_records',
    sa.Column('personnel_id', sa.Uuid(), nullable=False),
    sa.Column('credential_type', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('number_masked', sa.String(length=200), nullable=True),
    sa.Column('number_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_fact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_records.id'], name=op.f('fk_credential_records_personnel_id_personnel_records')),
    sa.ForeignKeyConstraint(['source_fact_id'], ['extracted_facts.id'], name=op.f('fk_credential_records_source_fact_id_extracted_facts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_records'))
    )
    op.create_index(op.f('ix_credential_records_credential_type'), 'credential_records', ['credential_type'], unique=False)
    op.create_index(op.f('ix_credential_records_number_hmac'), 'credential_records', ['number_hmac'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('relevance', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_finding_evidence_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_evidence_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding_evidence')),
    sa.UniqueConstraint('finding_id', 'evidence_id', name='finding_evidence_pair')
    )
    op.create_table('personnel_aliases',
    sa.Column('personnel_id', sa.Uuid(), nullable=False),
    sa.Column('alias_masked', sa.String(length=200), nullable=False),
    sa.Column('alias_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_records.id'], name=op.f('fk_personnel_aliases_personnel_id_personnel_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personnel_aliases'))
    )
    op.create_index(op.f('ix_personnel_aliases_alias_hmac'), 'personnel_aliases', ['alias_hmac'], unique=False)
    op.create_table('social_security_references',
    sa.Column('personnel_id', sa.Uuid(), nullable=False),
    sa.Column('employer_name_masked', sa.String(length=300), nullable=True),
    sa.Column('employer_name_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('account_masked', sa.String(length=100), nullable=True),
    sa.Column('account_hmac', sa.LargeBinary(length=32), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('source_fact_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_source', sa.String(length=64), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel_records.id'], name=op.f('fk_social_security_references_personnel_id_personnel_records')),
    sa.ForeignKeyConstraint(['source_fact_id'], ['extracted_facts.id'], name=op.f('fk_social_security_references_source_fact_id_extracted_facts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_security_references'))
    )
    op.create_index(op.f('ix_social_security_references_account_hmac'), 'social_security_references', ['account_hmac'], unique=False)
    op.create_index(op.f('ix_social_security_references_employer_name_hmac'), 'social_security_references', ['employer_name_hmac'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_security_references_employer_name_hmac'), table_name='social_security_references')
    op.drop_index(op.f('ix_social_security_references_account_hmac'), table_name='social_security_references')
    op.drop_table('social_security_references')
    op.drop_index(op.f('ix_personnel_aliases_alias_hmac'), table_name='personnel_aliases')
    op.drop_table('personnel_aliases')
    op.drop_table('finding_evidence')
    op.drop_index(op.f('ix_credential_records_number_hmac'), table_name='credential_records')
    op.drop_index(op.f('ix_credential_records_credential_type'), table_name='credential_records')
    op.drop_table('credential_records')
    op.drop_index(op.f('ix_personnel_records_project_id'), table_name='personnel_records')
    op.drop_index(op.f('ix_personnel_records_name_hmac'), table_name='personnel_records')
    op.drop_index(op.f('ix_personnel_records_bidder_id'), table_name='personnel_records')
    op.drop_table('personnel_records')
    op.drop_index(op.f('ix_evidence_document_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_review_decisions_finding_id'), table_name='review_decisions')
    op.drop_index('ix_review_decision_finding_created', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_model_call_logs_run_id'), table_name='model_call_logs')
    op.drop_table('model_call_logs')
    op.drop_index(op.f('ix_extracted_facts_sensitive_value_hmac'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_run_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_fact_type'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_document_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_document_versions_sha256'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_cross_document_matches_project_id'), table_name='cross_document_matches')
    op.drop_index(op.f('ix_cross_document_matches_match_type'), table_name='cross_document_matches')
    op.drop_table('cross_document_matches')
    op.drop_index(op.f('ix_source_documents_sha256'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_document_type'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_processing_tasks_trace_id'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_task_type'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_status'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_run_id'), table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_index(op.f('ix_generated_reports_project_id'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_code'), table_name='findings')
    op.drop_index(op.f('ix_findings_risk_level'), table_name='findings')
    op.drop_index(op.f('ix_findings_project_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_processing_runs_status'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_project_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_bidders_unified_credit_code_hmac'), table_name='bidders')
    op.drop_table('bidders')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('rule_versions')
    op.drop_table('roles')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
